# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-15 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfile',
            name='name',
        ),
    ]
