# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-17 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocall', '0002_surveyresponse_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='question_id',
        ),
        migrations.AddField(
            model_name='response',
            name='question_id',
            field=models.CharField(default='abcd', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='phone_number',
            field=models.CharField(default=123456789, max_length=15),
            preserve_default=False,
        ),
    ]
